apiVersion: v1
kind: Secret
metadata:
  name: neo-ticket-service-secrets
type: Opaque
stringData:
  NEO_DB_URL: "jdbc:postgresql://CHANGEME-production-postgres-host:5432/neoticket"
  NEO_DB_USER: "CHANGEME-production"
  NEO_DB_PASSWORD: "CHANGEME-production"
  NEO_JWT_SECRET: "CHANGEME-production-generate-a-random-32-plus-character-secret"
