apiVersion: v1
kind: Secret
metadata:
  name: neo-ticket-service-secrets
  labels:
    app.kubernetes.io/name: neo-ticket-service
type: Opaque
stringData:
  NEO_DB_URL: "jdbc:postgresql://CHANGEME-postgres-host:5432/neoticket"
  NEO_DB_USER: "CHANGEME"
  NEO_DB_PASSWORD: "CHANGEME"
  NEO_JWT_SECRET: "CHANGEME-generate-a-random-32-plus-character-secret"
